require_relative '../models/sequence'

# https://projecteuler.net/problem=2
class Solution2

  def solve
    fibonacci_sequence = Sequence.new(0, [1, 2]) { |s| s[-1] + s[-2] }
    fibonacci_sequence.upto(4000000).select(&:even?).reduce(:+)
  end

  def describe
    return <<-DESC
      Each new term in the Fibonacci sequence is generated by adding the
      previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
      By considering the terms in the Fibonacci sequence whose values do
      not exceed four million, find the sum of the even-valued terms.
    DESC
  end

end